console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")

console.log("ha hai")

console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")

console.log("ha hai")
console.log("ha hai")
console.log("qwerty")
console.log("ss")
console.log("wert")