console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")

console.log("ha hai")

console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")
console.log("ha hai")

console.log("ha hai")
console.log("ha hai")
console.log("qwerty")